# Use the official Node.js 14 image
FROM node:14

# Set the working directory in the container
WORKDIR /usr/src/app

# Copy package.json and package-lock.json to the working directory
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of the application code to the working directory
COPY . .

LABEL com.main.multicontainer="imos-recyclingapp" \
      com.required.configs="GUI_PORT" \
      com.user.display="True"

# Run the application
CMD ["node", "app.js"]
