name: 🔧 Improvement
description: Propose an enhancement to existing functionality
title: "[Improvement]: "
labels: ["enhancement"]

body:
  - type: markdown
    attributes:
      value: |
        Thank you for suggesting an improvement. Please provide the following details to help us understand your proposal.

  - type: textarea
    id: current_behavior
    attributes:
      label: Current Behavior
      description: Describe the current behavior that you think could be improved.
      placeholder: e.g., The search function only matches exact keywords.
    validations:
      required: true

  - type: textarea
    id: proposed_enhancement
    attributes:
      label: Proposed Enhancement
      description: Describe the enhancement you propose.
      placeholder: e.g., Implement fuzzy search to match partial keywords.
    validations:
      required: true

  - type: textarea
    id: benefits
    attributes:
      label: Benefits
      description: Explain the benefits of this improvement.
      placeholder: e.g., Users can find relevant results even with typos or partial matches.
    validations:
      required: true

  - type: textarea
    id: additional_context
    attributes:
      label: Additional Context
      description: Add any other context or screenshots about the improvement here.
      placeholder: e.g., Examples of fuzzy search in other applications.
    validations:
      required: false
