FROM nodered/node-red

# Install any additional dependencies if needed

# Copy Node-RED settings.js to preserve configuration
COPY settings.js /data/settings.js

# Expose the necessary ports
EXPOSE 1880
